### PR TITLE
Abstract app

### PR DESCRIPTION
**Pull request by PartMan7**

### CODE REVIEW

**Comment by SachdevJai** [comment]
> @SachdevJai when can you get this done?

what exactly do I need to get done?

**Comment by Goose-Of-War** [comment]
> > @SachdevJai when can you get this done?
> 
> what exactly do I need to get done?

Basically change the cases of
```js
switch (args[1]) {
    case '' : {...}
```
into individual `app.get` and `app.post` functions

**Comment by PartMan7** [comment]
Remember, if you run into any issues with this, hop by my room and I'll explain how it works!

You could bully Goose instead, if you so prefer, too

**Comment by PartMan7** [comment]
Ended up doing this myself since there was some blocking code on the mongoless rewrite. @SachdevJai could you pick up adding the error-route properly, instead?

**Pull request merged**
