### PR TITLE
Add automatic deploy scripts

### PR DESCRIPTION
**Pull request by PartMan7**
...still haven't decided whether to use a webhook or a deploy script for deploying to the Docker environment; will likely do the former

Implementation: Should `main` and `dev` be isolated containers or run in the same one? Leaning towards the former, since that way we can have insecure code on `dev` without worrying (which will have the config using generic member-level access)

### CODE REVIEW

**Comment by nishkalprakash** [comment]
What is preventing us from having 2 containers?

**Comment by Goose-Of-War** [comment]
Nothing specific ig. TBH I was inclined to two containers myself, considering `package.json` changes break the site and keeping it in one will just cause us hell

**Comment by PartMan7** [comment]
There's nothing fine particular I can think of, except maybe extra space consumption?

**Comment by nishkalprakash** [comment]
Great. No problem in having 2 containers then.

2 containers go brr...?

**Comment by PartMan7** [comment]
Yeeting this

**Pull request closed without merging**
