### PR TITLE
Feb Newsletter

### PR DESCRIPTION
**Pull request by PartMan7**

### CODE REVIEW

**Comment by Goose-Of-War** [comment]
Finally. Jan file was giving me the OCD to yeet it.
Probably could've gone `2023-02-0`

**Comment by nishkalprakash** [comment]
you should've said so.

I'd have yeet'd it

**Comment by Goose-Of-War** [comment]
It's your thing. I didn't want to nag over something like that.

~~Plus, there's a chance you'd have shoo'd me like you did when I was in Diplip and Gargi's threads~~

**Comment by Goose-Of-War** [comment]
Mokshith pulled an Uno reverse on me, which makes me the guy working on his part now ;-;

**Comment by PartMan7** [comment]
Working on his _what_

**Comment by Goose-Of-War** [comment]
Remind me to compress the images a bit. Currently it's over 7MB

**Comment by Goose-Of-War** [comment]
Uh... I think we forgot to get dev changes over here...

**Comment by Goose-Of-War** [comment]
@nishkalprakash can you have a look at whether the crossword looks fine now?

**Review by Goose-Of-War — APPROVED** [review]
If anything breaks, blame @nishkalprakash

**Pull request merged**
