### PR TITLE
Fandom-quiz

### PR DESCRIPTION
**Pull request by nishkalprakash**
Goos plz test once and merge with dev

### CODE REVIEW

**Comment by Goose-Of-War** [comment]
Reopen PR is a feature lol. You could've just opened it

**Comment by nishkalprakash** [comment]
whats done is done now.

**Comment by Goose-Of-War** [comment]
Back navigation? :|

**Comment by nishkalprakash** [comment]
will work on that next

**Comment by PartMan7** [comment]
Reminder for the checklist:

* Timer update (frontend)
* Total time taken tracked on backend
* Quiz frontend redesign - back nagivation, appearance, image layout (options)
* Audio/video support
* Third-party hosting for large files
* More intuitive/attractive results page

**Comment by Goose-Of-War** [comment]
@nishkalprakash merging this into `dev` for now. We'll make the PR in the fork

**Pull request merged**
